-- CreateEnum
CREATE TYPE "Elo" AS ENUM ('UNRANKED', 'IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'EMERALD', 'DIAMOND', 'MASTER', 'GRANDMASTER', 'CHALLENGER');

-- AlterTable
ALTER TABLE "LolAccount" ADD COLUMN     "elo" "Elo" NOT NULL DEFAULT 'UNRANKED';
